### ISSUE TITLE
wysiwyg-images with problems if media behind a symlink

### ISSUE THREAD

**Issue by nhp** [cloudinary/cloudinary_magento#15]
We encountered a strange behavior with the cms-image-synchronisation because the wrong image_names (pathes) got into the cloudinary_synchronisation table. 
After some investigations we found out that `Mage::helper('cms/wysiwyg_images')->getStorageRoot()` yielded the real_path of the symlinked file.
As that file was written into the filesystem-collection and compared with the database entries the extension never found any synced wysiwyg images and tired to sync everything again, resulting in more and more database entries, because after a sync/already exists it got written with the wrong path (realpath prepended with /media) into the table. 
#14 fixes this by using not the real_path but the path Mage::getBaseDir() is returning so the pathes from the database and the ones from the filesystem-collection can be the same again.

**Comment by eyalktCloudinary** [comment]
Closing due to time elapsed.
