### ISSUE TITLE
Error in logs: Strict Notice: Declaration of Cloudinary_Cloudinary_Model_Cache::save() should be compatible with Mage_Core_Model_Abstract::save() in public_html/app/code/community/Cloudinary/Cloudinary/Model/Cache.php on line 0

### ISSUE THREAD

**Issue by ProxiBlue** [cloudinary/cloudinary_magento#26]
Hi,

as per subject: lots of occurrences of error:

`Strict Notice: Declaration of Cloudinary_Cloudinary_Model_Cache::save() should be compatible with Mage_Core_Model_Abstract::save() in public_html/app/code/community/Cloudinary/Cloudinary/Model/Cache.php on line 0`

Magento ver. 1.9.3.2 with all patches up-to-date to latest.

**Comment by idobarnoam** [comment]
Hi @ProxiBlue 

Could you provide additional details regarding how are you receiving the errors?
Is it during installation, or while trying to deliver images? Something else?

Also, could you please upgrade Magento to 1.9.3.6 at least and see if you are still getting these errors?

Let us know?

**Comment by ProxiBlue** [comment]
Hi,

Error is produced during active usage of site, and images are loaded by client access, so i woudl say, during delivery of images. The errors appear in system.log (magento log file)

Glancing at the error, i would say that it involves saving information into the cloudinary magento cache.

Your code: 
```Cloudinary_Cloudinary_Model_Cache::function save($key, $value)```
core:
```Mage_Core_Model_Abstract::function save()````

Unfortunately upgrading a magento site is not a frivolous task, and requires some work, extensive testing, which my client is not currently ready for this procedure.

Anyhow, looking at the latest code (from magento 1.9.3.8) via open-mage mirror, I can for sure say the issue would remain...

https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Core/Model/Abstract.php#L302

**Comment by idobarnoam** [comment]
Hi @ProxiBlue 

Thanks for letting us know.

We have an open request with our dev team to look into this.

As soon as there will be any updates, we will be happy to let you know.

**Comment by ProxiBlue** [comment]
Thanks.

Would be great to get this resolved as soon as possible, as an urgency. Logs are being saturated and causing a large volume of logging, which essentially slows the site down, having to take the time to log out so much.

![image](https://user-images.githubusercontent.com/4994260/37631995-09d02e92-2c27-11e8-8435-b134b82c601b.png)

**Comment by ProxiBlue** [comment]
I have up on their module a long time ago.
The fact it completely breaks admin due to media folder symlinks...

**Comment by idobarnoam** [comment]
@speedupmate and @ProxiBlue This issue was handled in the latest release so we are closing this.
Please let us know if you experience something else.
