### ISSUE TITLE
Some images are not served from Cloudinary

### ISSUE THREAD

**Issue by jahvi** [cloudinary/cloudinary_magento#29]
I just started using the extension and it's worked well so far, mostly on product images, however I noticed that some images don't get served from Cloudinary, eg: category images, logo, etc.

Is there any helper function or something I can use in the code to make sure the image is used from Cloudinary and not my server?

Great work on the extension btw!

**Comment by idobarnoam** [comment]
Hi @jahvi,

Thanks for the kind words :)

The images that are being delivered using our Magento module are the ones that appear in the media folder. If the images don't appear there, then they would indeed won't be delivered via Cloudinary.

If there are any particular images you are experiencing issues with, please open a request at support@cloudinary.com and we could take a closer look.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
