### ISSUE TITLE
Installing latest version causes admin menu to dissapeer

### ISSUE THREAD

**Issue by CosyStudios** [cloudinary/cloudinary_magento#30]
Installed the extension via Magento connect using https://connect20.magentocommerce.com/c1b490ed2f887a5e9e7536e0a63fd69b/cloudinary+Cloudinary_Cloudinary-2.8.3
Successfully. 

However, when returning to admin, the entire admin menu has vanished. Can still see the dashboard, though cant seem to access other admin pages. 
(cache off, no compilation etc, obvious stuff)

Inspector reveals, the admin menu isnt just hidden, its never generated. 

Removing code/community/Cloudinary/* resolves.

Using Magento ver. 1.9.3.8

Any ideas?

**Comment by CosyStudios** [comment]
Sorry to be clear, Removing code/community/Cloudinary/* does notresolve the issue, just stops the module from loading !!!

**Comment by idobarnoam** [comment]
Hey @CosyStudios its, not something that we heard of prior to this case.

Would it be possible to share the credentials of your environment with us so we could take a closer look?

You could open a request at support@cloudinary.com and we could check this on our end as well.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
