### ISSUE TITLE
Non existant classes

### ISSUE THREAD

**Issue by iva-fullers** [cloudinary/cloudinary_magento#31]
When I am running:

setup:di:compile

I am getting this:

`Class Cloudinary\Api does not exist`

And in Admin if I try to save config I am getting that Cloudinary class is not defined, and it is used in:

`/app/code/Cloudinary/Cloudinary/Core/Security/CloudinaryEnvironmentVariable.php`

Am I missing some library or what is it?

I am having Magento2 Commerce Cloud solution.

**Comment by idobarnoam** [comment]
Hi @iva-fullers 

The error might mean that Magento has not loaded the Cloudinary PHP library that the Cloudinary Magento module uses.

To install it manually run the composer [require command](https://getcomposer.org/doc/03-cli.md#require) from your Magento installation root directory:

`Composer require cloudinary/cloudinary_php:1.8.0`
