### ISSUE TITLE
M1 Indexing Issue

### ISSUE THREAD

**Issue by MikeDevs** [cloudinary/cloudinary_magento#32]
Has anyone else experienced an issue with re-indexing from the command line with this extension? I just switched a Magento 1.9.3.9 store to Cloudinary and after installing the latest extension version our reindex job is failing with the following error:

```
PHP Fatal error:  Interface 'CloudinaryExtension\ConfigurationInterface' not found in app/code/community/Cloudinary/Cloudinary/Model/Configuration.php on line 16
```

The extension is otherwise working just fine. Issue with the autoloader when running via the cli maybe?

**Comment by strausr** [comment]
The error might mean that Magento has not loaded the Cloudinary PHP library that the Cloudinary Magento module uses.

To install it manually run the composer require command from your Magento installation root directory:
https://getcomposer.org/doc/03-cli.md#require

**Comment by MikeDevs** [comment]
It seems to be loading it and working normally via the backend. I was able to temporarily work around it after reading a PR addressing the autoloader by adding a call to the helper in the indexer.php shell script.

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
