### ISSUE TITLE
Change Preference for Plugin for class: Magento\Widget\Model\Template\Filter

### ISSUE THREAD

**Issue by osrecio** [cloudinary/cloudinary_magento#33]
In this module exists a preference of `Magento\Widget\Model\Template\Filter` to overwrite a method: `mediaDirective`.

Since this method exists in core, it is advisable to use Magento 2 plugin instead of using preference.

**Comment by idobarnoam** [comment]
Thanks, @osrecio  for bringing this to our attention.

We'll take this internally and see how to apply this.

**Comment by osrecio** [comment]
I created new issue in the specific [repository for Magento 2](https://github.com/cloudinary/cloudinary_magento2)
