### ISSUE TITLE
Warning: The use statement with non-compound name 'Cloudinary' has no effect...

### ISSUE THREAD

**Issue by andyt** [cloudinary/cloudinary_magento#44]
... in /var/www/htdocs/.modman/cloudinary_magento/app/code/community/Cloudinary/Cloudinary/Model/System/Config/Credentials.php on line 4

Encountered using PHP 7.2.11.

**Comment by idobarnoam** [comment]
@andyt Thanks for letting us know.
We will take a look into this.

Is the module working properly on your end?

**Comment by andyt** [comment]
Yes, it appears to be. I've disabled warnings.

**Comment by idobarnoam** [comment]
@andyt Thanks for confirming. 

We have an open request with the relevant team members to look into this in the next version release.

We will update the thread with any updates.

**Comment by eyalktCloudinary** [comment]
Closing due to time elapsed. Seems to be fixed.
