### ISSUE TITLE
Select Images from Media Gallery

### ISSUE THREAD

**Issue by infabo** [cloudinary/cloudinary_magento#5]
Hi!

I have a feature request.
When editing a Magento product media gallery (in Admin Panel of course) it would be really nice to be able to choose/assign from existing images in the Cloudinary Media Gallery (in addition to the Magento "standard upload files"-feature).

Thanks for your attention!

**Comment by taragano** [comment]
Hi,
I've passed it on to our dev team to consider adding such a feature in the future.
Thank you for your suggestion.

**Comment by grantkemp** [comment]
Hi @infabo , I am working with @taragano  on putting together the next version. I really like that idea and we have had a similar thoughts.  

Can you share some ideas/ use cases that you want to use it for so we can see if we can cover it? 

If you have other feature requests, please also get in touch.

**Comment by eyalktCloudinary** [comment]
Closing due to time elapsed.
