### ISSUE TITLE
Adding youtube and vimeo videos 

### ISSUE THREAD

**Issue by singh-prabh** [cloudinary/cloudinary_magento#60]
how can we add youtube and vimeo videos in image product gallery?

**Comment by igy** [comment]
Hi Prabh,

If you're using the Cloudinary Product Gallery Widget ( https://cloudinary.com/documentation/product_gallery ), it's not possible to load assets from another source like YouTube or Vimeo, but you can load videos from your Cloudinary account similarly to how you load images.

Also, this GitHub repository is for an older version of our plugin - if you're working on a new integration, I recommend using our newer plugin which is available here: https://marketplace.magento.com/cloudinary-cloudinary.html
You can also find our own documentation site here: https://cloudinary.com/documentation/magento_integration#overview

Thanks,
Stephen
