### ISSUE TITLE
"Unable to set target directory" Backend Error 

### ISSUE THREAD

**Issue by J-Silvestri** [cloudinary/cloudinary_magento#7]
Hello, when installing the extension everything goes fine, however when I first tried to access the Cloudinary > Manage panel in the backend main menu, I get the error "Unable to set target directory" and the first stack trace line:

> / var/www/dev1/htdocs/app/code/community/Cloudinary/Cloudinary/Model/Resource/Cms/Synchronisation/Collection.php(12): Varien_Data_Collection_Filesystem->addTargetDir('/var/www/dev1/htdocs/media/wysiwyg/')

I investigated and found that the media/wysiwyg/ directory did not exist on my fresh install of Magento 1.9.2.1. After creating the directory manually, the issue is resolved and the Cloudinary extension appears to function as expected.

I do not know if this issue was my own fault, but it seems Magento did not create this directory during installation and the Cloudinary extension assumes it exists.

**Comment by gimpe** [comment]
I confirm that creating the directory "web/media/wysiwyg" fixed this issue for me as well.

**Comment by taragano** [comment]
In case the Wysiwig folder is missing, the possible solutions for that are:

+ If one of these folders doesn't exist, create it
+ Ignore that the folder might not exist and go on as if nothing happened. We suggest to go with this solution, as the folder's non-existence simply means there is nothing to migrate from there.

Please let us know if you need any further assistacne

**Comment by J-Silvestri** [comment]
@taragano 

As I mentioned in my original post, the non-existence of the wysiwyg folder created an error that couldn’t be bypassed until I created the missing folder, thus **ignoring it is not an option. You cannot get past the error.**

This was meant as a bug report, not a question.

**Comment by grantkemp** [comment]
@J-Silvestri I had the same issue on a previous install. Magento should create the folder automatically when you upload via CMS. You should then be able to use the plugin fine. 

 If it doesn't then this article on stackexchange should help. 
http://magento.stackexchange.com/questions/15751/missing-wysiwyg-folder-in-magento

**Comment by idobarnoam** [comment]
@J-Silvestri In the latest version of the plugin, this issue was also handled.
There's a verification now checking whether the folder exists.
