### ISSUE TITLE
about INSTALL.md and composer

### ISSUE THREAD

**Issue by eduardo-g-silva** [cloudinary/cloudinary_magento#8]
Hi i am a bit confuse,

Is this package the same repo,
"connect20/Cloudinary_Cloudinary": "1.1.0"

If it is can be nice to change it in the install.md,

Thanks,

**Comment by taragano** [comment]
I'm sorry for my response delay.

Our Magento module can be found in here too:
https://www.magentocommerce.com/magento-connect/cloudinary-image-management-in-the-cloud.html

I'm sorry, but I'm not sure whether that's the `connect20` module you referred to.

**Comment by grantkemp** [comment]
@taragano  suggest we just remove the reference to the version number in the install MD.  Its pretty clear what the latest version is.  

This should be picked up in the next release 

@eduardo-g-silva  - thanks for pointing it out - its confusing!

**Comment by nadavofi** [comment]
Closing after shifting to Magento marketplace and due to time elapsed.
Please feel free to reopen the issue if yet it's still relevant.
